<?php

namespace TulipeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * WhoamiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WhoamiRepository extends EntityRepository
{
}
