modele_index:
    path:     /
    defaults: { _controller: "TulipeBundle:Modele:index" }
    methods:  GET


modele_new:
    path:    /new
    defaults: { _controller: "TulipeBundle:Modele:new" }
    methods:  [GET, POST]

modele_edit:
    path:     /{id}/edit
    defaults: { _controller: "TulipeBundle:Modele:edit" }
    methods:  [GET, POST]

modele_delete:
    path:     /{id}/delete
    defaults: { _controller: "TulipeBundle:Modele:delete" }
    methods:  DELETE
# Indique que la valeur du MODELE à récupérer est un NOMBRE
    requirements:
      id: \d+
