whoami_index:
    path:     /
    defaults: { _controller: "TulipeBundle:Whoami:index" }
    methods:  GET

whoami_show:
    path:     /{id}/show
    defaults: { _controller: "TulipeBundle:Whoami:show" }
    methods:  GET

whoami_new:
    path:     /new
    defaults: { _controller: "TulipeBundle:Whoami:new" }
    methods:  [GET, POST]

whoami_edit:
    path:     /{id}/edit
    defaults: { _controller: "TulipeBundle:Whoami:edit" }
    methods:  [GET, POST]

whoami_delete:
    path:     /{id}/delete
    defaults: { _controller: "TulipeBundle:Whoami:delete" }
    methods:  DELETE
