
modele_index:
    path:     /
    defaults: { _controller: "TulipeBundle:Modele:index" }
    methods:  GET

#-----------------------------------------------------------------------------------------------------
#Appel route utilisateur/client
#-----------------------------------------------------------------------------------------------------

user_routing:
    resource: routing/user.yml
    prefix:   /

#-----------------------------------------------------------------------------------------------------
#Appel route admin
#------------

tulipe_categorie:
    resource: "@TulipeBundle/Resources/config/routing/categorie.yml"
    prefix:   admin/categorie

tulipe_modele:
    resource: "@TulipeBundle/Resources/config/routing/modele.yml"
    prefix:   admin/modele

tulipe_whoami:
    resource: "@TulipeBundle/Resources/config/routing/whoami.yml"
    prefix:   admin/whoami


tulipe_homepage:
    path:     /
    defaults: { _controller: TulipeBundle:Default:index }

#-----------------------------------------------------------------------------------------------------
#Route accueil admin
#-----------------------------------------------------------------------------------------------------

admin_homepage:
    path:     /admin
    defaults: { _controller: TulipeBundle:Default:admin }