TulipeBundle\Entity\Modele:
    type: entity
    table: null
    repositoryClass: TulipeBundle\Repository\ModeleRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        content:
            type: text

    lifecycleCallbacks: {  }
    manyToOne:
        categorie:
            targetEntity: TulipeBundle\Entity\Categorie
        image:
            targetEntity: TulipeBundle\Entity\Image
            cascade: ["persist", "remove"]